name: ci

on:
  push:
    branches:
      - v-8.10.0

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0']
      fail-fast: false
    name: PHP ${{ matrix.php }}

    steps:
      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: bash tests/ci.sh
        env:
          CI_PHP_VERSION: ${{ matrix.php }}
